version: '3.7'

services:
  odoo:
    image: odoo:18.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: ["odoo", "-i", "base", "--database", "odoo"]
    volumes:
      - ./odoo:/mnt/extra-addons
      - ./config:/etc/odoo

  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

